name: Docker MySQL Images GitHub workflow

on:
  pull_request:
    branches:
      - 'master'
      - 'v1'
  push:
    branches:
      - 'master'
      - 'v1'
  schedule:
    - cron: '43 5 * * 0'

jobs:
  build_test_maybe_release:
    strategy:
      matrix:
        include:
          - mysql_version: '5.7'
          - mysql_version: '8.0'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Login to DockerHub
        # Merge ~ push.
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, test and push
        env:
          EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MYSQL_VERSION="${{ matrix.mysql_version }}" ./build-and-test.sh
          docker images | grep thecodingmachine/mysql
